//! Smithy-aligned input validation for RDS Query-protocol actions.
//!
//! Generated negative conformance probes hit every action with three
//! synthetic shapes: an omitted required member, an out-of-range string
//! length, and an invalid enum value. The historical handler chain in
//! `service.rs` / `extras.rs` accepts these without complaint because the
//! per-handler `required_query_param` / `get_param` calls were uneven and a
//! few actions (e.g. role-management shortcuts that flow through
//! `xml_empty_action`) skipped validation entirely.
//!
//! This module exposes one entry point, [`prevalidate`], which the service
//! handler runs before dispatching. The table inside is hand-derived from
//! the RDS Smithy model (`aws-models/rds.json`). Each entry lists:
//!
//!   * **required** — Query parameter names with `@required` on the input
//!     shape. Missing or empty values return `MissingParameter`.
//!   * **strings**  — `(name, min, max)` triples for members carrying
//!     `@length` constraints. Empty values are skipped (they would already
//!     be caught by `required`).
//!   * **enums**    — `(name, &[allowed])` tuples for members whose target
//!     is a Smithy `enum` shape. Values outside the set return
//!     `InvalidParameterValue`.
//!
//! Only validations the autogenerated probe actually exercises are listed.
//! Everything else is deliberately left out: hand-coded handlers downstream
//! still own business-logic checks, and we do not want to drift from AWS
//! by tightening rules the probe does not assert.

use crate::service::{invalid_param, missing_param};
use fakecloud_core::service::{AwsRequest, AwsServiceError};

/// Constraint table entry for one Query action.
struct OpConstraints {
    required: &'static [&'static str],
    strings: &'static [(&'static str, u64, u64)],
    enums: &'static [(&'static str, &'static [&'static str])],
}

/// Validate the request against the Smithy input shape for `action`.
/// Returns `Ok(())` when the action has no entry or every constraint
/// passes; otherwise returns the appropriate `MissingParameter` /
/// `InvalidParameterValue` AWS error.
pub(crate) fn prevalidate(action: &str, req: &AwsRequest) -> Result<(), AwsServiceError> {
    let Some(spec) = lookup(action) else {
        return Ok(());
    };

    for name in spec.required {
        match req.query_params.get(*name) {
            Some(value) if !value.is_empty() => {}
            _ => {
                // Also accept a member list of the form `<List>.member.1`
                // for Query list parameters (e.g. `VpcSubnetIds.member.1`),
                // because Smithy required-list members are sent that way.
                let prefix = format!("{name}.member.");
                let has_list_member = req.query_params.keys().any(|k| k.starts_with(&prefix));
                if !has_list_member {
                    return Err(missing_param(name));
                }
            }
        }
    }

    for (name, min, max) in spec.strings {
        if let Some(value) = req.query_params.get(*name) {
            if value.is_empty() {
                continue;
            }
            let len = value.chars().count() as u64;
            if len < *min || len > *max {
                return Err(invalid_param(&format!(
                    "{name} length {len} is outside the valid range {min}-{max}",
                )));
            }
        }
    }

    for (name, allowed) in spec.enums {
        if let Some(value) = req.query_params.get(*name) {
            if value.is_empty() {
                continue;
            }
            if !allowed.iter().any(|a| *a == value) {
                return Err(invalid_param(&format!(
                    "{name} value '{value}' is not one of the supported enum values",
                )));
            }
        }
    }

    Ok(())
}

/// Per-action constraint lookup. Returns `None` for actions that do not
/// need centralized validation (their per-handler code already does it).
fn lookup(action: &str) -> Option<OpConstraints> {
    Some(match action {
        "AddRoleToDBCluster" => OpConstraints {
            required: &["DBClusterIdentifier", "RoleArn"],
            strings: &[],
            enums: &[],
        },
        "AddRoleToDBInstance" => OpConstraints {
            required: &["DBInstanceIdentifier", "RoleArn", "FeatureName"],
            strings: &[],
            enums: &[],
        },
        "RemoveRoleFromDBCluster" => OpConstraints {
            required: &["DBClusterIdentifier", "RoleArn"],
            strings: &[],
            enums: &[],
        },
        "RemoveRoleFromDBInstance" => OpConstraints {
            required: &["DBInstanceIdentifier", "RoleArn", "FeatureName"],
            strings: &[],
            enums: &[],
        },
        "AddSourceIdentifierToSubscription" => OpConstraints {
            required: &["SubscriptionName", "SourceIdentifier"],
            strings: &[],
            enums: &[],
        },
        "RemoveSourceIdentifierFromSubscription" => OpConstraints {
            required: &["SubscriptionName", "SourceIdentifier"],
            strings: &[],
            enums: &[],
        },
        "CancelExportTask" => OpConstraints {
            required: &["ExportTaskIdentifier"],
            strings: &[],
            enums: &[],
        },
        "CopyDBClusterParameterGroup" => OpConstraints {
            required: &[
                "SourceDBClusterParameterGroupIdentifier",
                "TargetDBClusterParameterGroupIdentifier",
                "TargetDBClusterParameterGroupDescription",
            ],
            strings: &[],
            enums: &[],
        },
        "CopyDBParameterGroup" => OpConstraints {
            required: &[
                "SourceDBParameterGroupIdentifier",
                "TargetDBParameterGroupIdentifier",
                "TargetDBParameterGroupDescription",
            ],
            strings: &[],
            enums: &[],
        },
        "CopyDBSnapshot" => OpConstraints {
            required: &["SourceDBSnapshotIdentifier", "TargetDBSnapshotIdentifier"],
            strings: &[],
            enums: &[],
        },
        "CopyOptionGroup" => OpConstraints {
            required: &[
                "SourceOptionGroupIdentifier",
                "TargetOptionGroupIdentifier",
                "TargetOptionGroupDescription",
            ],
            strings: &[],
            enums: &[],
        },
        "CreateCustomDBEngineVersion" => OpConstraints {
            required: &["Engine", "EngineVersion"],
            strings: &[
                ("DatabaseInstallationFilesS3BucketName", 3, 63),
                ("DatabaseInstallationFilesS3Prefix", 1, 255),
                ("Description", 1, 1000),
                ("Engine", 1, 35),
                ("EngineVersion", 1, 60),
                ("ImageId", 1, 255),
                ("KMSKeyId", 1, 2048),
                ("Manifest", 1, 51000),
                ("SourceCustomDbEngineVersionIdentifier", 1, 255),
            ],
            enums: &[],
        },
        "CreateDBCluster" => OpConstraints {
            required: &["DBClusterIdentifier", "Engine"],
            strings: &[("GlobalClusterIdentifier", 1, 255)],
            enums: &[
                ("ClusterScalabilityType", &["standard", "limitless"]),
                ("DatabaseInsightsMode", &["standard", "advanced"]),
                ("MasterUserAuthenticationType", &["password", "iam-db-auth"]),
            ],
        },
        "CreateDBClusterEndpoint" => OpConstraints {
            required: &[
                "DBClusterIdentifier",
                "DBClusterEndpointIdentifier",
                "EndpointType",
            ],
            strings: &[],
            enums: &[],
        },
        "CreateDBClusterParameterGroup" => OpConstraints {
            required: &[
                "DBClusterParameterGroupName",
                "DBParameterGroupFamily",
                "Description",
            ],
            strings: &[],
            enums: &[],
        },
        "CreateDBProxy" => OpConstraints {
            // List-typed required members (VpcSubnetIds, Auth) are emitted
            // by the probe as an empty form list, which produces no
            // `<name>.member.N` keys. AWS would also error on empty list,
            // but the resulting `MissingParameter` is not in this op's
            // Smithy error_shapes — leave the list check to the handler
            // and validate only scalar members here.
            required: &["DBProxyName", "EngineFamily", "RoleArn"],
            strings: &[("DBProxyName", 1, 63), ("RoleArn", 1, 2048)],
            enums: &[],
        },
        "CreateDBProxyEndpoint" => OpConstraints {
            // VpcSubnetIds is a required list — see note on CreateDBProxy.
            required: &["DBProxyName", "DBProxyEndpointName"],
            strings: &[("DBProxyName", 1, 63), ("DBProxyEndpointName", 1, 63)],
            enums: &[],
        },
        "DeleteDBProxy" => OpConstraints {
            required: &["DBProxyName"],
            strings: &[("DBProxyName", 1, 63)],
            enums: &[],
        },
        "DeleteDBProxyEndpoint" => OpConstraints {
            required: &["DBProxyEndpointName"],
            strings: &[("DBProxyEndpointName", 1, 63)],
            enums: &[],
        },
        "DescribeDBProxies" => OpConstraints {
            required: &[],
            strings: &[("DBProxyName", 1, 63)],
            enums: &[],
        },
        "DescribeDBProxyEndpoints" => OpConstraints {
            required: &[],
            strings: &[("DBProxyName", 1, 63), ("DBProxyEndpointName", 1, 63)],
            enums: &[],
        },
        "DescribeDBProxyTargets" => OpConstraints {
            required: &["DBProxyName"],
            strings: &[("DBProxyName", 1, 63), ("TargetGroupName", 1, 63)],
            enums: &[],
        },
        "DescribeDBProxyTargetGroups" => OpConstraints {
            required: &["DBProxyName"],
            strings: &[("DBProxyName", 1, 63), ("TargetGroupName", 1, 63)],
            enums: &[],
        },
        "RegisterDBProxyTargets" => OpConstraints {
            required: &["DBProxyName"],
            strings: &[("DBProxyName", 1, 63), ("TargetGroupName", 1, 63)],
            enums: &[],
        },
        "DeregisterDBProxyTargets" => OpConstraints {
            required: &["DBProxyName"],
            strings: &[("DBProxyName", 1, 63), ("TargetGroupName", 1, 63)],
            enums: &[],
        },
        "ModifyDBProxyTargetGroup" => OpConstraints {
            required: &["TargetGroupName", "DBProxyName"],
            strings: &[("DBProxyName", 1, 63), ("TargetGroupName", 1, 63)],
            enums: &[],
        },
        "CreateDBSecurityGroup" => OpConstraints {
            required: &["DBSecurityGroupName", "DBSecurityGroupDescription"],
            strings: &[],
            enums: &[],
        },
        "CreateDBShardGroup" => OpConstraints {
            required: &["DBShardGroupIdentifier", "DBClusterIdentifier", "MaxACU"],
            strings: &[],
            enums: &[],
        },
        "DeleteDBShardGroup" => OpConstraints {
            required: &["DBShardGroupIdentifier"],
            strings: &[("DBShardGroupIdentifier", 1, 63)],
            enums: &[],
        },
        "ModifyDBShardGroup" => OpConstraints {
            required: &["DBShardGroupIdentifier"],
            strings: &[("DBShardGroupIdentifier", 1, 63)],
            enums: &[],
        },
        "RebootDBShardGroup" => OpConstraints {
            required: &["DBShardGroupIdentifier"],
            strings: &[("DBShardGroupIdentifier", 1, 63)],
            enums: &[],
        },
        "DescribeDBShardGroups" => OpConstraints {
            required: &[],
            strings: &[("DBShardGroupIdentifier", 1, 63)],
            enums: &[],
        },
        "CreateEventSubscription" => OpConstraints {
            required: &["SubscriptionName", "SnsTopicArn"],
            strings: &[],
            enums: &[],
        },
        "CreateGlobalCluster" => OpConstraints {
            required: &[],
            strings: &[("GlobalClusterIdentifier", 1, 255)],
            enums: &[],
        },
        "DeleteGlobalCluster" => OpConstraints {
            required: &["GlobalClusterIdentifier"],
            strings: &[("GlobalClusterIdentifier", 1, 255)],
            enums: &[],
        },
        "ModifyGlobalCluster" => OpConstraints {
            required: &["GlobalClusterIdentifier"],
            strings: &[("GlobalClusterIdentifier", 1, 255)],
            enums: &[],
        },
        "RemoveFromGlobalCluster" => OpConstraints {
            required: &["GlobalClusterIdentifier", "DbClusterIdentifier"],
            strings: &[],
            enums: &[],
        },
        "FailoverGlobalCluster" => OpConstraints {
            required: &["GlobalClusterIdentifier", "TargetDbClusterIdentifier"],
            strings: &[
                ("GlobalClusterIdentifier", 1, 255),
                ("TargetDbClusterIdentifier", 1, 255),
            ],
            enums: &[],
        },
        "SwitchoverGlobalCluster" => OpConstraints {
            required: &["GlobalClusterIdentifier", "TargetDbClusterIdentifier"],
            strings: &[
                ("GlobalClusterIdentifier", 1, 255),
                ("TargetDbClusterIdentifier", 1, 255),
            ],
            enums: &[],
        },
        "DescribeGlobalClusters" => OpConstraints {
            required: &[],
            strings: &[("GlobalClusterIdentifier", 1, 255)],
            enums: &[],
        },
        "CreateIntegration" => OpConstraints {
            required: &["SourceArn", "TargetArn", "IntegrationName"],
            strings: &[
                ("DataFilter", 1, 25600),
                // IntegrationDescription is min=0 — skip min/max guard since
                // min=0 means an empty value is allowed and the probe's
                // negative_too_short test relies on min>0 to fire.
                ("IntegrationName", 1, 63),
                ("SourceArn", 1, 255),
                ("TargetArn", 20, 2048),
            ],
            enums: &[],
        },
        "DeleteIntegration" => OpConstraints {
            required: &["IntegrationIdentifier"],
            strings: &[("IntegrationIdentifier", 1, 255)],
            enums: &[],
        },
        "ModifyIntegration" => OpConstraints {
            required: &["IntegrationIdentifier"],
            strings: &[
                ("IntegrationIdentifier", 1, 255),
                ("IntegrationName", 1, 63),
                ("DataFilter", 1, 25600),
            ],
            enums: &[],
        },
        // Describe* ops are intentionally absent: the only error they
        // declare is the per-resource `*NotFoundFault`, so surfacing a
        // length-bound `InvalidParameterValue` from prevalidate would be
        // undeclared. Per-handler logic returns the right resource-not-
        // found shape downstream.
        "CreateOptionGroup" => OpConstraints {
            required: &[
                "OptionGroupName",
                "EngineName",
                "MajorEngineVersion",
                "OptionGroupDescription",
            ],
            strings: &[],
            enums: &[],
        },
        "CreateTenantDatabase" => OpConstraints {
            required: &["DBInstanceIdentifier", "TenantDBName", "MasterUsername"],
            strings: &[],
            enums: &[],
        },
        "DeleteTenantDatabase" => OpConstraints {
            required: &["DBInstanceIdentifier", "TenantDBName"],
            strings: &[],
            enums: &[],
        },
        "DeleteCustomDBEngineVersion" => OpConstraints {
            required: &["Engine", "EngineVersion"],
            strings: &[("Engine", 1, 35), ("EngineVersion", 1, 60)],
            enums: &[],
        },
        "ModifyCustomDBEngineVersion" => OpConstraints {
            required: &["Engine", "EngineVersion"],
            strings: &[
                ("Engine", 1, 35),
                ("EngineVersion", 1, 60),
                ("Description", 1, 1000),
            ],
            enums: &[("Status", &["available", "inactive"])],
        },
        "DeleteDBClusterAutomatedBackup" => OpConstraints {
            required: &["DbClusterResourceId"],
            strings: &[],
            enums: &[],
        },
        "DescribeDBClusterBacktracks" => OpConstraints {
            required: &["DBClusterIdentifier"],
            strings: &[],
            enums: &[],
        },
        "DescribeDBClusterSnapshotAttributes" => OpConstraints {
            required: &["DBClusterSnapshotIdentifier"],
            strings: &[],
            enums: &[],
        },
        "DescribeDBSnapshotAttributes" => OpConstraints {
            required: &["DBSnapshotIdentifier"],
            strings: &[],
            enums: &[],
        },
        "ModifyDBClusterSnapshotAttribute" => OpConstraints {
            required: &["DBClusterSnapshotIdentifier", "AttributeName"],
            strings: &[],
            enums: &[],
        },
        "ModifyDBSnapshotAttribute" => OpConstraints {
            required: &["DBSnapshotIdentifier", "AttributeName"],
            strings: &[],
            enums: &[],
        },
        "ModifyDBClusterParameterGroup" => OpConstraints {
            required: &["DBClusterParameterGroupName", "Parameters"],
            strings: &[],
            enums: &[],
        },
        "ModifyCurrentDBClusterCapacity" => OpConstraints {
            required: &["DBClusterIdentifier"],
            strings: &[],
            enums: &[],
        },
        "ModifyDBRecommendation" => OpConstraints {
            required: &["RecommendationId"],
            strings: &[],
            enums: &[],
        },
        "ModifyDBSnapshot" => OpConstraints {
            required: &["DBSnapshotIdentifier"],
            strings: &[],
            enums: &[],
        },
        "DescribeDBMajorEngineVersions" => OpConstraints {
            required: &[],
            strings: &[
                ("Engine", 1, 35),
                ("MajorEngineVersion", 1, 60),
                ("Marker", 1, 1024),
            ],
            enums: &[],
        },
        "DescribeBlueGreenDeployments" => OpConstraints {
            required: &[],
            strings: &[("BlueGreenDeploymentIdentifier", 1, 255)],
            enums: &[],
        },
        "DescribeExportTasks" => OpConstraints {
            required: &[],
            strings: &[("ExportTaskIdentifier", 1, 255), ("SourceArn", 1, 2048)],
            enums: &[("SourceType", &["SNAPSHOT", "CLUSTER"])],
        },
        "DescribeOptionGroupOptions" => OpConstraints {
            required: &["EngineName"],
            strings: &[],
            enums: &[],
        },
        "DescribeOrderableDBInstanceOptions" => OpConstraints {
            required: &["Engine"],
            strings: &[],
            enums: &[],
        },
        "DescribeValidDBInstanceModifications" => OpConstraints {
            required: &["DBInstanceIdentifier"],
            strings: &[],
            enums: &[],
        },
        "DescribeEngineDefaultClusterParameters" => OpConstraints {
            required: &["DBParameterGroupFamily"],
            strings: &[],
            enums: &[],
        },
        "DescribeEngineDefaultParameters" => OpConstraints {
            required: &["DBParameterGroupFamily"],
            strings: &[],
            enums: &[],
        },
        "DisableHttpEndpoint" => OpConstraints {
            required: &["ResourceArn"],
            strings: &[],
            enums: &[],
        },
        "EnableHttpEndpoint" => OpConstraints {
            required: &["ResourceArn"],
            strings: &[],
            enums: &[],
        },
        "PurchaseReservedDBInstancesOffering" => OpConstraints {
            required: &["ReservedDBInstancesOfferingId"],
            strings: &[],
            enums: &[],
        },
        "RestoreDBClusterFromS3" => OpConstraints {
            required: &[
                "DBClusterIdentifier",
                "Engine",
                "MasterUsername",
                "S3BucketName",
                "S3IngestionRoleArn",
                "SourceEngine",
                "SourceEngineVersion",
            ],
            strings: &[],
            enums: &[],
        },
        "StartActivityStream" => OpConstraints {
            required: &["ResourceArn", "KmsKeyId", "Mode"],
            strings: &[],
            enums: &[],
        },
        "StopActivityStream" => OpConstraints {
            required: &["ResourceArn"],
            strings: &[],
            enums: &[],
        },
        "ModifyActivityStream" => OpConstraints {
            required: &[],
            strings: &[],
            enums: &[],
        },
        "StartDBInstanceAutomatedBackupsReplication" => OpConstraints {
            required: &["SourceDBInstanceArn"],
            strings: &[],
            enums: &[],
        },
        "StopDBInstanceAutomatedBackupsReplication" => OpConstraints {
            required: &["SourceDBInstanceArn"],
            strings: &[],
            enums: &[],
        },
        "StartExportTask" => OpConstraints {
            required: &[
                "ExportTaskIdentifier",
                "SourceArn",
                "S3BucketName",
                "IamRoleArn",
                "KmsKeyId",
            ],
            strings: &[],
            enums: &[],
        },
        _ => return None,
    })
}
