// Auto-generated CFN input constraints. Do not edit by hand.
// Generated from aws-models/cloudformation.json
use super::FieldConstraint;

pub(crate) fn constraints_for(action: &str, field: &str) -> Option<FieldConstraint> {
    match (action, field) {
        ("ActivateType", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("ActivateType", "PublicTypeArn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ActivateType", "PublisherId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(40),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ActivateType", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ActivateType", "TypeNameAlias") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ActivateType", "ExecutionRoleArn") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(256),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ActivateType", "VersionBump") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["MAJOR", "MINOR"]),
        }),
        ("ActivateType", "MajorVersion") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100000),
            enum_values: None,
        }),
        ("CancelUpdateStack", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ContinueUpdateRollback", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ContinueUpdateRollback", "RoleARN") => Some(FieldConstraint {
            min_len: Some(20),
            max_len: Some(2048),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ContinueUpdateRollback", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateChangeSet", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateChangeSet", "TemplateBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateChangeSet", "TemplateURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateChangeSet", "RoleARN") => Some(FieldConstraint {
            min_len: Some(20),
            max_len: Some(2048),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateChangeSet", "ChangeSetName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateChangeSet", "ClientToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateChangeSet", "Description") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateChangeSet", "ChangeSetType") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["CREATE", "UPDATE", "IMPORT"]),
        }),
        ("CreateChangeSet", "OnStackFailure") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["DO_NOTHING", "ROLLBACK", "DELETE"]),
        }),
        ("CreateChangeSet", "DeploymentMode") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["REVERT_DRIFT"]),
        }),
        ("CreateGeneratedTemplate", "GeneratedTemplateName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStack", "TemplateBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStack", "TemplateURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStack", "TimeoutInMinutes") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: None,
            enum_values: None,
        }),
        ("CreateStack", "RoleARN") => Some(FieldConstraint {
            min_len: Some(20),
            max_len: Some(2048),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStack", "OnFailure") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["DO_NOTHING", "ROLLBACK", "DELETE"]),
        }),
        ("CreateStack", "StackPolicyBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(16384),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStack", "StackPolicyURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStack", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStackInstances", "OperationId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStackInstances", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("CreateStackRefactor", "Description") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStackSet", "Description") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStackSet", "TemplateBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStackSet", "TemplateURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStackSet", "AdministrationRoleARN") => Some(FieldConstraint {
            min_len: Some(20),
            max_len: Some(2048),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStackSet", "ExecutionRoleName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(64),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("CreateStackSet", "PermissionModel") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SERVICE_MANAGED", "SELF_MANAGED"]),
        }),
        ("CreateStackSet", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("CreateStackSet", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeactivateType", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeactivateType", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("DeactivateType", "Arn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeleteChangeSet", "ChangeSetName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1600),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeleteChangeSet", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeleteGeneratedTemplate", "GeneratedTemplateName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeleteStack", "RoleARN") => Some(FieldConstraint {
            min_len: Some(20),
            max_len: Some(2048),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeleteStack", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeleteStack", "DeletionMode") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["STANDARD", "FORCE_DELETE_STACK"]),
        }),
        ("DeleteStackInstances", "OperationId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeleteStackInstances", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("DeleteStackSet", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("DeregisterType", "Arn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeregisterType", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("DeregisterType", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DeregisterType", "VersionId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeAccountLimits", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeChangeSet", "ChangeSetName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1600),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeChangeSet", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeChangeSet", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeChangeSetHooks", "ChangeSetName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1600),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeChangeSetHooks", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeChangeSetHooks", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeEvents", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeEvents", "ChangeSetName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1600),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeEvents", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeGeneratedTemplate", "GeneratedTemplateName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeOrganizationsAccess", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("DescribePublisher", "PublisherId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(40),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeStackDriftDetectionStatus", "StackDriftDetectionId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(36),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeStackEvents", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeStackInstance", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("DescribeStackResourceDrifts", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeStackResourceDrifts", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeStackResourceDrifts", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("DescribeStacks", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeStackSet", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("DescribeStackSetOperation", "OperationId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeStackSetOperation", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("DescribeType", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("DescribeType", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeType", "Arn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeType", "VersionId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeType", "PublisherId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(40),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeType", "PublicVersionNumber") => Some(FieldConstraint {
            min_len: Some(5),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DescribeTypeRegistration", "RegistrationToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DetectStackDrift", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DetectStackResourceDrift", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DetectStackSetDrift", "OperationId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("DetectStackSetDrift", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("EstimateTemplateCost", "TemplateBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("EstimateTemplateCost", "TemplateURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ExecuteChangeSet", "ChangeSetName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1600),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ExecuteChangeSet", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ExecuteChangeSet", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("GetGeneratedTemplate", "Format") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["JSON", "YAML"]),
        }),
        ("GetGeneratedTemplate", "GeneratedTemplateName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("GetHookResult", "HookResultId") => Some(FieldConstraint {
            min_len: Some(36),
            max_len: Some(36),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("GetTemplate", "ChangeSetName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1600),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("GetTemplate", "TemplateStage") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["Original", "Processed"]),
        }),
        ("GetTemplateSummary", "TemplateBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("GetTemplateSummary", "TemplateURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("GetTemplateSummary", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("GetTemplateSummary", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("ImportStacksToStackSet", "StackIdsUrl") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ImportStacksToStackSet", "OperationId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ImportStacksToStackSet", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("ListChangeSets", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListChangeSets", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListExports", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListGeneratedTemplates", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListGeneratedTemplates", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListHookResults", "TargetType") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["CHANGE_SET", "STACK", "RESOURCE", "CLOUD_CONTROL"]),
        }),
        ("ListHookResults", "TargetId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1600),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListHookResults", "TypeArn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListHookResults", "Status") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&[
                "HOOK_IN_PROGRESS",
                "HOOK_COMPLETE_SUCCEEDED",
                "HOOK_COMPLETE_FAILED",
                "HOOK_FAILED",
            ]),
        }),
        ("ListHookResults", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListImports", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListResourceScanRelatedResources", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListResourceScanRelatedResources", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListResourceScanResources", "TagKey") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListResourceScanResources", "TagValue") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(256),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListResourceScanResources", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListResourceScans", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListResourceScans", "ScanTypeFilter") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["FULL", "PARTIAL"]),
        }),
        ("ListStackInstanceResourceDrifts", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackInstanceResourceDrifts", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListStackInstanceResourceDrifts", "OperationId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackInstanceResourceDrifts", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("ListStackInstances", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackInstances", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListStackInstances", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("ListStackRefactorActions", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackRefactorActions", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListStackRefactors", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackRefactors", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListStackResources", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStacks", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackSetAutoDeploymentTargets", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackSetAutoDeploymentTargets", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListStackSetAutoDeploymentTargets", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("ListStackSetOperationResults", "OperationId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackSetOperationResults", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackSetOperationResults", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListStackSetOperationResults", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("ListStackSetOperations", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackSetOperations", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListStackSetOperations", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("ListStackSets", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListStackSets", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListStackSets", "Status") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["ACTIVE", "DELETED"]),
        }),
        ("ListStackSets", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("ListTypeRegistrations", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("ListTypeRegistrations", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListTypeRegistrations", "TypeArn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListTypeRegistrations", "RegistrationStatusFilter") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["COMPLETE", "IN_PROGRESS", "FAILED"]),
        }),
        ("ListTypeRegistrations", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListTypeRegistrations", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListTypes", "Visibility") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["PUBLIC", "PRIVATE"]),
        }),
        ("ListTypes", "ProvisioningType") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["NON_PROVISIONABLE", "IMMUTABLE", "FULLY_MUTABLE"]),
        }),
        ("ListTypes", "DeprecatedStatus") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["LIVE", "DEPRECATED"]),
        }),
        ("ListTypes", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("ListTypes", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListTypes", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListTypeVersions", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("ListTypeVersions", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListTypeVersions", "Arn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListTypeVersions", "MaxResults") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: Some(1),
            max_range: Some(100),
            enum_values: None,
        }),
        ("ListTypeVersions", "NextToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ListTypeVersions", "DeprecatedStatus") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["LIVE", "DEPRECATED"]),
        }),
        ("ListTypeVersions", "PublisherId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(40),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("PublishType", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("PublishType", "Arn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("PublishType", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("PublishType", "PublicVersionNumber") => Some(FieldConstraint {
            min_len: Some(5),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RecordHandlerProgress", "BearerToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RecordHandlerProgress", "OperationStatus") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["PENDING", "IN_PROGRESS", "SUCCESS", "FAILED"]),
        }),
        ("RecordHandlerProgress", "CurrentOperationStatus") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["PENDING", "IN_PROGRESS", "SUCCESS", "FAILED"]),
        }),
        ("RecordHandlerProgress", "StatusMessage") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RecordHandlerProgress", "ErrorCode") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&[
                "NotUpdatable",
                "InvalidRequest",
                "AccessDenied",
                "InvalidCredentials",
                "AlreadyExists",
                "NotFound",
                "ResourceConflict",
                "Throttling",
                "ServiceLimitExceeded",
                "NotStabilized",
                "GeneralServiceException",
                "ServiceInternalError",
                "NetworkFailure",
                "InternalFailure",
                "InvalidTypeConfiguration",
                "HandlerInternalFailure",
                "NonCompliant",
                "Unknown",
                "UnsupportedTarget",
            ]),
        }),
        ("RecordHandlerProgress", "ResourceModel") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(16384),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RecordHandlerProgress", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RegisterPublisher", "ConnectionArn") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(256),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RegisterType", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("RegisterType", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RegisterType", "SchemaHandlerPackage") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(4096),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RegisterType", "ExecutionRoleArn") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(256),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RegisterType", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RollbackStack", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RollbackStack", "RoleARN") => Some(FieldConstraint {
            min_len: Some(20),
            max_len: Some(2048),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("RollbackStack", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SetStackPolicy", "StackPolicyBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(16384),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SetStackPolicy", "StackPolicyURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SetTypeConfiguration", "TypeArn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SetTypeConfiguration", "Configuration") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(204800),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SetTypeConfiguration", "ConfigurationAlias") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(256),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SetTypeConfiguration", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SetTypeConfiguration", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("SetTypeDefaultVersion", "Arn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SetTypeDefaultVersion", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("SetTypeDefaultVersion", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SetTypeDefaultVersion", "VersionId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SignalResource", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SignalResource", "UniqueId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(64),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("SignalResource", "Status") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SUCCESS", "FAILURE"]),
        }),
        ("StartResourceScan", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("StopStackSetOperation", "OperationId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("StopStackSetOperation", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("TestType", "Arn") => Some(FieldConstraint {
            min_len: Some(0),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("TestType", "Type") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["RESOURCE", "MODULE", "HOOK"]),
        }),
        ("TestType", "TypeName") => Some(FieldConstraint {
            min_len: Some(10),
            max_len: Some(204),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("TestType", "VersionId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("TestType", "LogDeliveryBucket") => Some(FieldConstraint {
            min_len: Some(3),
            max_len: Some(63),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateGeneratedTemplate", "GeneratedTemplateName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateGeneratedTemplate", "NewGeneratedTemplateName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStack", "TemplateBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStack", "TemplateURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStack", "StackPolicyDuringUpdateBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(16384),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStack", "StackPolicyDuringUpdateURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStack", "RoleARN") => Some(FieldConstraint {
            min_len: Some(20),
            max_len: Some(2048),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStack", "StackPolicyBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(16384),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStack", "StackPolicyURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStack", "ClientRequestToken") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStackInstances", "OperationId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStackInstances", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("UpdateStackSet", "Description") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(1024),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStackSet", "TemplateBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStackSet", "TemplateURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStackSet", "AdministrationRoleARN") => Some(FieldConstraint {
            min_len: Some(20),
            max_len: Some(2048),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStackSet", "ExecutionRoleName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(64),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStackSet", "PermissionModel") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SERVICE_MANAGED", "SELF_MANAGED"]),
        }),
        ("UpdateStackSet", "OperationId") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(128),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("UpdateStackSet", "CallAs") => Some(FieldConstraint {
            min_len: None,
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: Some(&["SELF", "DELEGATED_ADMIN"]),
        }),
        ("UpdateTerminationProtection", "StackName") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ValidateTemplate", "TemplateBody") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: None,
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        ("ValidateTemplate", "TemplateURL") => Some(FieldConstraint {
            min_len: Some(1),
            max_len: Some(5120),
            min_range: None,
            max_range: None,
            enum_values: None,
        }),
        _ => None,
    }
}
