//! Smithy-aligned input validation for Bedrock control-plane actions.
//!
//! Generated negative conformance probes hit every JSON action with three
//! synthetic shapes: an omitted required field, an out-of-range string
//! length / integer range, and an invalid enum value. The historical
//! handlers in `customization.rs`, `evaluation.rs`, `guardrails.rs`, etc.
//! validated only a handful of identifiers and let everything else pass
//! through with default values, so negative variants returned HTTP 201
//! / HTTP 200 instead of the declared `ValidationException`.
//!
//! [`prevalidate`] is invoked at the top of the service dispatcher with
//! the resolved action name, the parsed JSON body, and the request's
//! query parameters. The constraint table is hand-derived from
//! `aws-models/bedrock.json` and only covers the constraints the
//! autogenerated probe actually exercises; per-handler logic downstream
//! still owns the business-rule checks.
//!
//! All errors emerge as the standard `ValidationException` shape declared
//! on every Bedrock op that needs one.

use http::StatusCode;
use serde_json::Value;

use fakecloud_core::service::{AwsRequest, AwsServiceError};

/// Constraint table entry for one Bedrock control-plane action.
struct OpConstraints {
    /// JSON body fields that must be present and non-empty.
    required: &'static [&'static str],
    /// `(field, min, max)` length constraints applied to string fields in
    /// the request body. Skipped when the field is absent.
    strings: &'static [(&'static str, u64, u64)],
    /// `(field, allowed_values)` checks for enum-typed body fields.
    enums: &'static [(&'static str, &'static [&'static str])],
    /// `(field, min, max)` constraints applied to integer body fields.
    integers: &'static [(&'static str, i64, i64)],
    /// `(query_param, min, max)` length constraints on httpQuery members.
    query_strings: &'static [(&'static str, u64, u64)],
    /// `(query_param, min, max)` integer-range checks on httpQuery
    /// members (typically `maxResults`).
    query_integers: &'static [(&'static str, i64, i64)],
    /// `(query_param, allowed_values)` for enum-typed httpQuery members.
    query_enums: &'static [(&'static str, &'static [&'static str])],
}

const EMPTY: OpConstraints = OpConstraints {
    required: &[],
    strings: &[],
    enums: &[],
    integers: &[],
    query_strings: &[],
    query_integers: &[],
    query_enums: &[],
};

/// Run Smithy-aligned prevalidation on `req` for the resolved Bedrock
/// `action`. Returns `Ok(())` for actions with no entry in the table or
/// when every constraint is satisfied; otherwise emits a
/// `ValidationException` matching the wire shape declared on the op.
pub(crate) fn prevalidate(action: &str, req: &AwsRequest) -> Result<(), AwsServiceError> {
    let Some(spec) = lookup(action) else {
        return Ok(());
    };

    let body = req.json_body();

    // Required body fields: a missing key OR a JSON `null` is treated as
    // absent. Empty strings, empty arrays, and empty objects are rejected
    // because the probe builds them as the "required omitted" stand-in
    // when the field's target shape carries a `@length` min > 0 / a
    // structure with required members.
    for field in spec.required {
        match body.get(*field) {
            None | Some(Value::Null) => {
                return Err(validation_error(&format!("{field} is required",)))
            }
            Some(Value::String(s)) if s.is_empty() => {
                return Err(validation_error(&format!("{field} must not be empty")));
            }
            Some(Value::Array(a)) if a.is_empty() => {
                return Err(validation_error(&format!("{field} must not be empty")));
            }
            Some(Value::Object(o)) if o.is_empty() => {
                return Err(validation_error(&format!("{field} must not be empty")));
            }
            _ => {}
        }
    }

    for (field, min, max) in spec.strings {
        if let Some(Value::String(s)) = body.get(*field) {
            // Empty strings count as zero-length and fail when `min > 0`.
            // Optional fields that allow empty values are declared with
            // `min == 0` in the table.
            let len = s.chars().count() as u64;
            if len < *min || len > *max {
                return Err(validation_error(&format!(
                    "{field} length {len} is outside the valid range {min}-{max}",
                )));
            }
        }
    }

    for (field, allowed) in spec.enums {
        if let Some(Value::String(s)) = body.get(*field) {
            if !s.is_empty() && !allowed.iter().any(|a| *a == s) {
                return Err(validation_error(&format!(
                    "{field} value '{s}' is not one of the supported enum values",
                )));
            }
        }
    }

    for (field, min, max) in spec.integers {
        if let Some(v) = body.get(*field) {
            if let Some(n) = v.as_i64() {
                if n < *min || n > *max {
                    return Err(validation_error(&format!(
                        "{field} value {n} is outside the valid range {min}-{max}",
                    )));
                }
            } else if let Some(n) = v.as_f64() {
                if !n.is_finite() {
                    return Err(validation_error(&format!(
                        "{field} must be a finite number"
                    )));
                }
                let i = n as i64;
                if i < *min || i > *max {
                    return Err(validation_error(&format!(
                        "{field} value {n} is outside the valid range {min}-{max}",
                    )));
                }
            }
        }
    }

    for (name, min, max) in spec.query_strings {
        if let Some(value) = req.query_params.get(*name) {
            let len = value.chars().count() as u64;
            if len < *min || len > *max {
                return Err(validation_error(&format!(
                    "{name} length {len} is outside the valid range {min}-{max}",
                )));
            }
        }
    }

    for (name, min, max) in spec.query_integers {
        if let Some(value) = req.query_params.get(*name) {
            if let Ok(parsed) = value.parse::<i64>() {
                if parsed < *min || parsed > *max {
                    return Err(validation_error(&format!(
                        "{name} value {parsed} is outside the valid range {min}-{max}",
                    )));
                }
            }
        }
    }

    for (name, allowed) in spec.query_enums {
        if let Some(value) = req.query_params.get(*name) {
            if !value.is_empty() && !allowed.iter().any(|a| *a == value) {
                return Err(validation_error(&format!(
                    "{name} value '{value}' is not one of the supported enum values",
                )));
            }
        }
    }

    Ok(())
}

fn validation_error(message: &str) -> AwsServiceError {
    AwsServiceError::aws_error(StatusCode::BAD_REQUEST, "ValidationException", message)
}

fn lookup(action: &str) -> Option<OpConstraints> {
    Some(match action {
        // ── Custom models ────────────────────────────────────────────
        "CreateCustomModel" => OpConstraints {
            required: &["modelName", "modelSourceConfig"],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("modelKmsKeyArn", 1, 2048),
                ("modelName", 1, 63),
                ("roleArn", 0, 2048),
            ],
            ..EMPTY
        },
        "ListCustomModels" => OpConstraints {
            query_strings: &[
                ("baseModelArnEquals", 1, 1011),
                ("foundationModelArnEquals", 1, 1011),
                ("nameContains", 1, 63),
            ],
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[
                ("isOwned", &["true", "false"]),
                ("modelStatus", &["Active", "Creating", "Failed"]),
                ("sortBy", &["CreationTime"]),
                ("sortOrder", &["Ascending", "Descending"]),
            ],
            ..EMPTY
        },
        "ListImportedModels" => OpConstraints {
            query_strings: &[("nameContains", 1, 63)],
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[
                ("sortBy", &["CreationTime"]),
                ("sortOrder", &["Ascending", "Descending"]),
            ],
            ..EMPTY
        },
        "ListCustomModelDeployments" => OpConstraints {
            query_strings: &[("modelArnEquals", 20, 1011), ("nameContains", 1, 63)],
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[
                ("statusEquals", &["Creating", "Active", "Failed"]),
                ("sortBy", &["CreationTime"]),
                ("sortOrder", &["Ascending", "Descending"]),
            ],
            ..EMPTY
        },

        // ── Custom model deployments ─────────────────────────────────
        "CreateCustomModelDeployment" => OpConstraints {
            required: &["modelArn", "modelDeploymentName"],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("description", 1, 200),
                ("modelArn", 20, 1011),
                ("modelDeploymentName", 1, 63),
            ],
            ..EMPTY
        },
        "UpdateCustomModelDeployment" => OpConstraints {
            required: &["modelArn"],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("description", 1, 200),
                ("modelArn", 20, 1011),
            ],
            ..EMPTY
        },

        // ── Customization jobs ───────────────────────────────────────
        "CreateModelCustomizationJob" => OpConstraints {
            required: &[
                "baseModelIdentifier",
                "customModelName",
                "jobName",
                "outputDataConfig",
                "roleArn",
                "trainingDataConfig",
            ],
            strings: &[
                ("baseModelIdentifier", 1, 2048),
                ("clientRequestToken", 1, 256),
                ("customModelKmsKeyId", 1, 2048),
                ("customModelName", 1, 63),
                ("jobName", 1, 63),
                ("roleArn", 0, 2048),
            ],
            enums: &[(
                "customizationType",
                &[
                    "FINE_TUNING",
                    "CONTINUED_PRE_TRAINING",
                    "DISTILLATION",
                    "IMPORTED",
                ],
            )],
            ..EMPTY
        },
        "ListModelCustomizationJobs" => OpConstraints {
            query_strings: &[("nameContains", 1, 63)],
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[
                (
                    "statusEquals",
                    &["InProgress", "Completed", "Failed", "Stopping", "Stopped"],
                ),
                ("sortBy", &["CreationTime"]),
                ("sortOrder", &["Ascending", "Descending"]),
            ],
            ..EMPTY
        },

        // ── Evaluation jobs ─────────────────────────────────────────
        "CreateEvaluationJob" => OpConstraints {
            required: &[
                "evaluationConfig",
                "inferenceConfig",
                "jobName",
                "outputDataConfig",
                "roleArn",
            ],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("customerEncryptionKeyId", 1, 2048),
                ("jobDescription", 1, 200),
                ("jobName", 1, 63),
                ("roleArn", 0, 2048),
            ],
            enums: &[("applicationType", &["ModelEvaluation", "RagEvaluation"])],
            ..EMPTY
        },
        "ListEvaluationJobs" => OpConstraints {
            query_strings: &[("nameContains", 1, 63)],
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[
                (
                    "applicationTypeEquals",
                    &["ModelEvaluation", "RagEvaluation"],
                ),
                (
                    "statusEquals",
                    &[
                        "InProgress",
                        "Completed",
                        "Failed",
                        "Stopping",
                        "Stopped",
                        "Deleting",
                    ],
                ),
                ("sortBy", &["CreationTime"]),
                ("sortOrder", &["Ascending", "Descending"]),
            ],
            ..EMPTY
        },

        // ── Guardrails ───────────────────────────────────────────────
        "CreateGuardrail" => OpConstraints {
            required: &["blockedInputMessaging", "blockedOutputsMessaging", "name"],
            strings: &[
                ("blockedInputMessaging", 1, 500),
                ("blockedOutputsMessaging", 1, 500),
                ("clientRequestToken", 1, 256),
                ("description", 1, 200),
                ("kmsKeyId", 1, 2048),
                ("name", 1, 50),
            ],
            ..EMPTY
        },
        "ListGuardrails" => OpConstraints {
            query_strings: &[("guardrailIdentifier", 0, 2048)],
            query_integers: &[("maxResults", 1, 1000)],
            ..EMPTY
        },

        // ── Inference profiles ───────────────────────────────────────
        "CreateInferenceProfile" => OpConstraints {
            required: &["inferenceProfileName", "modelSource"],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("description", 1, 200),
                ("inferenceProfileName", 1, 64),
            ],
            ..EMPTY
        },
        "ListInferenceProfiles" => OpConstraints {
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[("typeEquals", &["SYSTEM_DEFINED", "APPLICATION"])],
            ..EMPTY
        },

        // ── Marketplace endpoints ────────────────────────────────────
        "CreateMarketplaceModelEndpoint" => OpConstraints {
            required: &["endpointConfig", "modelSourceIdentifier"],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("endpointName", 1, 63),
                ("modelSourceIdentifier", 1, 2048),
            ],
            ..EMPTY
        },
        "UpdateMarketplaceModelEndpoint" => OpConstraints {
            required: &["endpointConfig"],
            strings: &[("clientRequestToken", 1, 256)],
            ..EMPTY
        },
        "RegisterMarketplaceModelEndpoint" => OpConstraints {
            required: &["modelSourceIdentifier"],
            strings: &[("modelSourceIdentifier", 1, 2048)],
            ..EMPTY
        },
        "ListMarketplaceModelEndpoints" => OpConstraints {
            query_strings: &[("modelSourceEquals", 1, 2048)],
            query_integers: &[("maxResults", 1, 1000)],
            ..EMPTY
        },

        // ── Model copy / import / invocation jobs ────────────────────
        "CreateModelCopyJob" => OpConstraints {
            required: &["sourceModelArn", "targetModelName"],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("modelKmsKeyId", 1, 2048),
                ("sourceModelArn", 20, 1011),
                ("targetModelName", 1, 63),
            ],
            ..EMPTY
        },
        "ListModelCopyJobs" => OpConstraints {
            query_strings: &[
                ("sourceAccountEquals", 0, 50),
                ("sourceModelArnEquals", 20, 1011),
                ("targetModelNameContains", 1, 63),
            ],
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[
                ("statusEquals", &["InProgress", "Completed", "Failed"]),
                ("sortBy", &["CreationTime"]),
                ("sortOrder", &["Ascending", "Descending"]),
            ],
            ..EMPTY
        },
        "CreateModelImportJob" => OpConstraints {
            required: &["importedModelName", "jobName", "modelDataSource", "roleArn"],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("importedModelKmsKeyId", 1, 2048),
                ("importedModelName", 1, 63),
                ("jobName", 1, 63),
                ("roleArn", 0, 2048),
            ],
            ..EMPTY
        },
        "ListModelImportJobs" => OpConstraints {
            query_strings: &[("nameContains", 1, 63)],
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[
                ("statusEquals", &["InProgress", "Completed", "Failed"]),
                ("sortBy", &["CreationTime"]),
                ("sortOrder", &["Ascending", "Descending"]),
            ],
            ..EMPTY
        },
        "CreateModelInvocationJob" => OpConstraints {
            required: &[
                "inputDataConfig",
                "jobName",
                "modelId",
                "outputDataConfig",
                "roleArn",
            ],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("jobName", 1, 63),
                ("modelId", 1, 2048),
                ("roleArn", 0, 2048),
            ],
            enums: &[("modelInvocationType", &["BATCH"])],
            integers: &[("timeoutDurationInHours", 24, 168)],
            ..EMPTY
        },
        "ListModelInvocationJobs" => OpConstraints {
            query_strings: &[("nameContains", 1, 63)],
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[
                (
                    "statusEquals",
                    &[
                        "Submitted",
                        "InProgress",
                        "Completed",
                        "Failed",
                        "Stopping",
                        "Stopped",
                        "PartiallyCompleted",
                        "Expired",
                        "Validating",
                        "Scheduled",
                    ],
                ),
                ("sortBy", &["CreationTime"]),
                ("sortOrder", &["Ascending", "Descending"]),
            ],
            ..EMPTY
        },

        // ── Prompt routers ───────────────────────────────────────────
        "CreatePromptRouter" => OpConstraints {
            required: &[
                "fallbackModel",
                "models",
                "promptRouterName",
                "routingCriteria",
            ],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("description", 1, 200),
                ("promptRouterName", 1, 63),
            ],
            ..EMPTY
        },
        "ListPromptRouters" => OpConstraints {
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[("type", &["custom", "default"])],
            ..EMPTY
        },

        // ── Provisioned throughput ───────────────────────────────────
        "CreateProvisionedModelThroughput" => OpConstraints {
            required: &["modelId", "modelUnits", "provisionedModelName"],
            strings: &[
                ("clientRequestToken", 1, 256),
                ("modelId", 1, 2048),
                ("provisionedModelName", 1, 63),
            ],
            ..EMPTY
        },
        "ListProvisionedModelThroughputs" => OpConstraints {
            query_strings: &[("modelArnEquals", 20, 1011), ("nameContains", 1, 63)],
            query_integers: &[("maxResults", 1, 1000)],
            query_enums: &[
                (
                    "statusEquals",
                    &["Creating", "InService", "Updating", "Failed"],
                ),
                ("sortBy", &["CreationTime"]),
                ("sortOrder", &["Ascending", "Descending"]),
            ],
            ..EMPTY
        },

        // ── Foundation model agreements / availability ───────────────
        "CreateFoundationModelAgreement" => OpConstraints {
            required: &["modelId", "offerToken"],
            strings: &[("modelId", 1, 140)],
            ..EMPTY
        },
        "ListFoundationModelAgreementOffers" => OpConstraints {
            required: &["modelId"],
            query_strings: &[("modelId", 1, 140)],
            ..EMPTY
        },
        "GetFoundationModelAvailability" => OpConstraints {
            required: &["modelId"],
            query_strings: &[("modelId", 1, 140)],
            ..EMPTY
        },

        // ── Tags / resource policies ─────────────────────────────────
        "ListTagsForResource" => OpConstraints {
            required: &["resourceARN"],
            strings: &[("resourceARN", 20, 1011)],
            ..EMPTY
        },
        "UntagResource" => OpConstraints {
            required: &["resourceARN", "tagKeys"],
            strings: &[("resourceARN", 20, 1011)],
            ..EMPTY
        },
        "PutResourcePolicy" => OpConstraints {
            required: &["resourceArn", "resourcePolicy"],
            strings: &[("resourceArn", 1, 255)],
            ..EMPTY
        },

        // ── Enforced guardrails ──────────────────────────────────────
        "PutEnforcedGuardrailConfiguration" => OpConstraints {
            required: &["guardrailInferenceConfig"],
            ..EMPTY
        },

        // ── Automated reasoning ─────────────────────────────────────
        "ListAutomatedReasoningPolicies" => OpConstraints {
            query_strings: &[("policyArn", 0, 1024)],
            query_integers: &[("maxResults", 1, 100)],
            ..EMPTY
        },

        _ => return None,
    })
}
